import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { PlayerContextProvider } from '@/contexts/player';
import { AuthContextProvider } from '@/contexts/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} overflow-x-hidden bg-gray-50 text-gray-800 selection:bg-brand-button  selection:text-white`}
      >
        <AuthContextProvider>
          <PlayerContextProvider>{children}</PlayerContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
